export const labels = {
  en: {
    agents: "agents",
    waiting: "waiting",
    running: "running",
    errors: "errors",
    unread: "unread",
    offline: "offline",
    stale: "stale",
    unknown: "unknown",
    idle: "idle",
    starting: "starting",
    cancelling: "cancelling",
    failed: "failed",
    main: "Main checkout",
    default: "Default",
    detached: "Detached",
    createAgent: "Create agent",
    harness: "Harness",
    model: "Model",
    unavailable: "Unavailable",
    compatible: "Available",
    cancel: "Cancel",
    draft: "Draft",
    shared:
      "Agents in this workspace share the same files, Git index and build outputs. Concurrent writes may conflict.",
  },
  zh: {
    agents: "个 Agent",
    waiting: "待处理",
    running: "运行中",
    errors: "错误",
    unread: "未读完成",
    offline: "离线",
    stale: "已过期",
    unknown: "未知",
    idle: "空闲",
    starting: "启动中",
    cancelling: "取消中",
    failed: "失败",
    main: "主检出",
    default: "默认",
    detached: "游离检出",
    createAgent: "创建 Agent",
    harness: "Agent 类型",
    model: "模型",
    unavailable: "不可用",
    compatible: "可用",
    cancel: "取消",
    draft: "草稿",
    shared: "同一工作区的 Agent 共享文件、Git 索引和构建产物；并发写入可能冲突。",
  },
} as const;
export type SidebarLocale = keyof typeof labels;
